name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos-intel:
    name: build on intel
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install
        run: npm install

      - name: build electron
        run: npm run electron:build

      - name: zip dist folder
        run: |
          mkdir -p dist-zip
          zip -r dist-zip/nocturnal-intel.zip dist/

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-nocturnal-build
          path: dist-zip/nocturnal-intel.zip

  build-macos-silicon:
    name: build on silicon
    runs-on: macos-14
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install 
        run: npm install

      - name: build electron
        run: npm run electron:build

      - name: zip dist folder
        run: |
          mkdir -p dist-zip
          zip -r dist-zip/nocturnal-silicon.zip dist/

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-silicon-nocturnal-build
          path: dist-zip/nocturnal-silicon.zip
